clientId: clientid
clientSecret: clientsecret
projectId: projectid
databaseId: (default)
locationId: us-central1
appEngineService: rules-server
googleKeysUrl: https://www.googleapis.com/oauth2/v3/certs

displayVideo360:
  baseURL: https://localhost:8001/

firestore:
  baseURL: https://localhost:8002/

scheduler:
  baseURL: https://localhost:8003/
