clientId: clientid
clientSecret: clientsecret
projectId: projectid
databaseId: (default)
locationId: us-central1
appEngineService: rules-server
refreshTokenKey: refresh-token-key

displayVideo360:
  baseURL: https://localhost:8001/

firestore:
  baseURL: https://localhost:8002/

scheduler:
  baseURL: https://localhost:8003/
