clientId: $CLIENT_ID
clientSecret: $CLIENT_SECRET
projectId: $PROJECT_ID
databaseId: (default)

displayVideo360:
  baseURL: https://displayvideo.googleapis.com/

firestore:
  baseURL: https://firestore.googleapis.com/
